# Site Settings
title: Start Jekyll
email: oganianlab@posteo.de
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
url: "http://harivignesh03.github.io"
twitter_username: yoganian
github_username:  HVCLab
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
  ignore_theme_config: BOOL
